### ISSUE TITLE
phing is missing in centos based images

### ISSUE THREAD

**Issue by rtamarasinghe** [orangehrm/orangehrm-dev-environment#14]
phing is not installed in the centos based images (5.6).

earlier development images had the following in their docker file to install phing

RUN pear channel-discover pear.phing.info && \
    pear install VersionControl_SVN-alpha && \
    pear install phing/phing-2.6.1

**Comment by Nipuna-Sankalpa** [comment]
phing is available in both php 5.6 and 7.1 images.

**Comment by rshariffdeen** [comment]
@Nipuna-Sankalpa can you get the commit number and close this issue
