### ISSUE TITLE
Unable To Find Pages

### ISSUE THREAD

**Issue by VoltaTrainee** [orangehrm/orangehrm-dev-environment#20]
I have made custom style changes in the code and have also attached pictures that are running.
I want to add custom field and remove some but unable to find the codes to the pages HTML. Would appreciate if someone can help me find the location to the files of the webpages.

**Comment by ChanakaR** [comment]
Hi @VoltaTrainee ,
Are you referring to OrangeHRM open-source application or OrangeHRM development environment? According to my understanding, you are referring to the OrangeHRM application. If so, you are publishing your issue in the wrong place (This is the docker development environment for OrangeHRM). Please correct if I am wrong.

**Comment by VoltaTrainee** [comment]
Can you send a link to orangehrm development environemnt

**Comment by ChanakaR** [comment]
This is the dockerized orangehrm development environment. I hope you are referring to the OrangeHRM application, and not to the dev environment. This is just the development environment. You can contact the OrangeHRM opensource teams from following links,

1) OrangeHRM Official FB page : https://www.facebook.com/OrangeHRM
2) OrangeHRM OS repo: https://github.com/orangehrm/orangehrm
